### ISSUE TITLE
部分视频出现错误：avformat_write_header

### ISSUE THREAD

**Issue by UzLung1435** [btnkij/qsv2flv#10]
对于使用爱奇艺帧绮映画（4K HDR）的视频，在转换至MP4格式时仅能播放前6分10秒，超过部分会直接报错，而转换至flv格式时会出现avformat_write_header错误。
使用1080P的qsv视频，则可以被正常转换为mp4或flv。

**Comment by jdnx** [comment]
这边目前1080p的也无法转换, 直接提示avformat write header error
