### ISSUE TITLE
大佬，这个东西，CSDN有人盗用了

### ISSUE THREAD

**Issue by moonlanm** [btnkij/qsv2flv#17]
https://blog.csdn.net/zxc514257857/article/details/71189451
![YIS5EM4$M~8UJ2}$3Z}_(EH](https://user-images.githubusercontent.com/62653345/199727941-35f56eca-f745-49ba-8c1b-d8c2da73c867.png)

**Comment by zeroclear** [comment]
张口就来，先不说本项目2018年创建的，文章是17年写的，总能看出界面不一样吧  
![证据1](https://user-images.githubusercontent.com/16979504/199787001-f7f829f4-ecbc-494c-914f-509bc590c86f.png)  
事实上这个双冠家园QSV格式转换器的原作者是[星沉地动](https://github.com/Jiangxiaogang/QSV2FLV)，项目虽然删了，但是仍能找到他很久之前的[格式分析](https://blog.csdn.net/qq446252221/article/details/7362348)  
![证据2](https://user-images.githubusercontent.com/16979504/199786970-0e967a95-7c22-4364-abae-d79f6d45eb9b.png)  
星沉地动的原版长这样，然后被人改了，拿去淘宝卖钱，可能他很伤心就停更了  
他才是从头到尾的受害者，不光CSDN，[B站也有盗用的](https://www.bilibili.com/video/BV1T7411u7Qt)，还遇到了义愤填膺张冠李戴的人（CSDN评论区链接是你发的吧？）

**Comment by moonlanm** [comment]
> 张口就来，先不说本项目2018年创建的，文章是17年写的，总能看出界面不一样吧
> ![证据1](https://user-images.githubusercontent.com/16979504/199787001-f7f829f4-ecbc-494c-914f-509bc590c86f.png)
> 事实上这个双冠家园QSV格式转换器的原作者是[星沉地动](https://github.com/Jiangxiaogang/QSV2FLV)，项目虽然删了，但是仍能找到他很久之前的[格式分析](https://blog.csdn.net/qq446252221/article/details/7362348)
> ![证据2](https://user-images.githubusercontent.com/16979504/199786970-0e967a95-7c22-4364-abae-d79f6d45eb9b.png)
> 星沉地动的原版长这样，然后被人改了，拿去淘宝卖钱，可能他很伤心就停更了
> 他才是从头到尾的受害者，不光CSDN，[B站也有盗用的](https://www.bilibili.com/video/BV1T7411u7Qt)，还遇到了义愤填膺张冠李戴的人（CSDN评论区链接是你发的吧？）

如果你说的是真的，那我道歉是我没搞清楚就妄自揣测了。
